group 'com.sensorsdata.analytics.abtesting.abtesting_sdk_flutter'
version '1.0'

buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: 'com.android.library'
import com.android.Version
def agpVersion = Version.ANDROID_GRADLE_PLUGIN_VERSION
def needNamespace = agpVersion.tokenize('.')[0].toInteger() >= 7 &&
        agpVersion.tokenize('.')[1].toInteger() >= 3
println ">>> Current AGP Version: $agpVersion"

android {
    compileSdkVersion 30
    if (needNamespace) {
        namespace 'com.sensorsdata.analytics.abtesting.abtesting_sdk_flutter'
    }

    defaultConfig {
        minSdkVersion 16
    }
}
dependencies {
    api 'com.sensorsdata.analytics.abtesting:SensorsABTesting:latest.release'
}
